feat(settings): Set projen-managed topic for projen managed repositories through settings.yml [CU-8x8uu0gmy]
time-loop/clickup-projen pull request #148
Opened 2023-04-13 16:10 UTC by swyrwiak-cu

As discussed on https://click-up.slack.com/archives/C01SW5QG7PX/p1681229005165429 we will be using required workflows for repositories that are not managed by **projen**. 
I need a way to identify **projen** managed repositories. I want to do it through topics, that can be set on the repo level and then parsed through `gh api`

2023-04-14 18:05 UTC, nathanhruby commented on test/github-settings.test.ts
> +    expect(synth['.github/workflows/semgrep.yml']).toMatchSnapshot();
I don't grok how semgrep gets added here?  shouldn't this be settings.yml?

2023-04-14 18:05 UTC, nathanhruby commented on src/github-settings.ts
> +  export const REPOSITORY_TOPICS = 'projen-managed';
if this is a list, can we make it one now?

2023-04-17 19:28 UTC, ahammond requested changes

2023-04-17 19:28 UTC, ahammond commented on src/github-settings.ts
> +export module gitHubSettings {
Missing docstring. This is library code. Must at the very least reference https://github.com/apps/settings

2023-04-17 19:28 UTC, ahammond commented on test/github-settings.test.ts
> +    expect(synth['.github/workflows/semgrep.yml']).toMatchSnapshot();
The semgrep stuff should be in a different PR, I think. Maybe is?

2023-04-19 11:38 UTC, swyrwiak-cu commented on test/github-settings.test.ts
> +    expect(synth['.github/workflows/semgrep.yml']).toMatchSnapshot();
There is a separate PR that adds `semgrep` to `projen` and it's https://github.com/time-loop/clickup-projen/pull/147

2023-05-07 01:32 UTC, closed without merging